name: Playwright Tests
on:
  workflow_dispatch:
  schedule:
    - cron: 35 01 * * *
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html
      - name: Ensure browsers are installed
        run: python -m playwright install --with-deps
      - name: Run your tests
        run: pytest test_kadai.py -html=report.html --self-contained-html
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test_report
          path: report.html
